---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-bruol-tech
  namespace: default
spec:
  secretName: local-bruol-tech-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "*.local.bruol.tech"
  dnsNames:
  - "local.bruol.tech"
  - "*.local.bruol.tech"
