---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-bruol-me
  namespace: default
spec:
  secretName: local-bruol-me-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.local.bruol.me"
  dnsNames:
  - "local.bruol.me"
  - "*.local.bruol.me"
