apiVersion: apps/v1
kind: Deployment
metadata:
  name: uptime-kuma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uptime-kuma
  template:
    metadata:
      labels:
        app: uptime-kuma
    spec:
      securityContext:
        runAsUser: 1003
        runAsGroup: 1003
        fsGroup: 1003
      containers:
      - name: uptime-kuma
        image: louislam/uptime-kuma
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 3001
        volumeMounts:
          - mountPath: /app/data
            name: uptime-kuma-data
      volumes:
        - name: uptime-kuma-data
          persistentVolumeClaim:
            claimName: uptime-kuma-pvc